# syntax=docker/dockerfile-upstream:experimental

FROM node:10

WORKDIR /app
ADD . .

# For some reason, npm with buildkit fails the first time, but
# works the second time. :shrug:
# https://stackoverflow.com/questions/15393821/npm-err-cb-never-called
RUN --mount=type=cache,target=/root/.npm npm install . || npm install .

ENTRYPOINT exit 0
