# Start builder
ARG copyImage="node:10"
FROM ${copyImage} as copier
RUN mkdir -p /app/node_modules

FROM node:10 as builder

WORKDIR /app
COPY --from=copier /app/node_modules /app/node_modules
ADD . .
RUN npm install .
# Done builder

# Start dir-cache
FROM node:10 as dir-cache
COPY --from=builder /app/node_modules /app/node_modules
# Done dir-cache

# Start main
FROM builder
ENTRYPOINT exit 0
# Done main
